mywebsite/comments/routes.py
from flask import redirect, url_for, request, abort, flash, current_app, Blueprint
from flask_login import current_user, login_required
from mywebsite import db
from mywebsite.models import Comment

comments = Blueprint('comments', __name__) #string comments is the directory comments, __name__ is where it located

#note that comment created in project route in the mywebsite/projects/routes.py
#but I can create comment route in this file by moving the code
#that take care create comment in mywebsite/projects/routes.py to this file

@comments.route('/comment/<int:comment_id>/update', methods=['POST'])
@login_required
def update_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    project_id= comment.project_id
    if comment.author != current_user:
        abort(403)
    comment.content = request.form['forming']
    db.session.commit()
    return redirect(url_for('projects.project', project_id=project_id))

@comments.route('/comment/<int:comment_id>/delete', methods=['POST'])
@login_required
def delete_comment(comment_id):
    admin_email = current_app.config['MAIL_USERNAME']
    comment = Comment.query.get_or_404(comment_id)
    project_id= comment.project_id
    if current_user.email != admin_email and current_user != comment.author:
        abort(403)
    db.session.delete(comment)
    db.session.commit()   
    flash('That comment has been deleted!', 'success')
    return redirect(url_for('projects.project', project_id=project_id))

mywebsite/main/routes.py
from flask import render_template, flash, redirect, url_for, request, abort, current_app, Blueprint
from flask_login import current_user, login_required
from mywebsite import db, limiter 
from mywebsite.models import Project, Home
from mywebsite.main.forms import HomeForm

main = Blueprint('main', __name__) #string main is the directory main, __name__ is where it located

@main.route('/')
@main.route('/home')
def home():
    home = Home.query.order_by(Home.id.desc()).first_or_404()
    admin_task = home.task
    admin_email = current_app.config['MAIL_USERNAME'] #admin email(this email in enviroment file)
    return render_template('home.html', admin_email=admin_email, admin_task=admin_task, home=home)

@main.route('/home/create', methods=['GET', 'POST'])
@login_required
@limiter.limit('5 per day', exempt_when= lambda : current_user.email == current_app.config['MAIL_USERNAME'])
def create_home():
    #query to last one
    home = Home.query.order_by(Home.id.desc()).first_or_404()
    admin_task = home.task
    admin_email = current_app.config['MAIL_USERNAME'] #admin email(this email in enviroment file)
    # only admin update home page
    if current_user.email != admin_email:
        abort(403)
    # check form is valid on submit
    form = HomeForm()
    if form.validate_on_submit():
        home = Home(greeting=form.greeting.data, position=form.position.data, about_me_overview=form.about_me_overview.data, about_me=form.about_me.data, task=form.task.data)
        db.session.add(home)
        db.session.commit()
        flash('New home has been created', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_home.html', title='About Me Create', form=form, admin_email=admin_email, admin_task=admin_task)

@main.route('/home/update', methods=['GET', 'POST'])
@login_required
@limiter.limit('5 per day', exempt_when= lambda : current_user.email == current_app.config['MAIL_USERNAME'])
def update_home():
    #query to last one
    admin = Home.query.order_by(Home.id.desc()).first_or_404()
    admin_task = admin.task
    admin_email = current_app.config['MAIL_USERNAME'] #admin email(this email in enviroment file)
    # only admin update home page
    if current_user.email != admin_email:
        abort(403)
    # check form is valid on submit
    form = HomeForm()
    if form.validate_on_submit():
        # save admin in the form to database
        admin.greeting = form.greeting.data
        admin.position = form.position.data
        admin.about_me_overview = form.about_me_overview.data
        admin.about_me = form.about_me.data
        admin.task = form.task.data
        db.session.commit()
        flash('Home has been updated!', 'success')
        return redirect(url_for('main.home'))
    elif request.method == 'GET':
        # popup value from the admin database to the update home page
        form.greeting.data = admin.greeting
        form.position.data = admin.position
        form.about_me_overview.data = admin.about_me_overview
        form.about_me.data = admin.about_me
        form.task.data = admin.task
    return render_template('update_home.html', title='About Me Update', admin_email=admin_email,  admin_task=admin_task, form=form)

@main.route('/home/before_delete')
@login_required
@limiter.limit('5 per day', exempt_when= lambda : current_user.email == current_app.config['MAIL_USERNAME'])
def before_delete_home():
    admin_email = current_app.config['MAIL_USERNAME'] #admin email(this email in enviroment file)
    # only admin to do flowing steps
    if current_user.email != admin_email:
        abort(403)
    # query all
    homes = Home.query.all() #home must contain at least 1 instance bc I created an instance before deploy this website
    if len(homes) <= 1:
        flash("There is only one home page in the database. I'm not allowed myself to delete this home", 'warning')
        return redirect(url_for('main.home'))
    admin_task = homes[-1].task
    return render_template('before_delete_home.html', title='About Me Delete', admin_email=admin_email, admin_task=admin_task, homes=homes, uniform=True)

@main.route('/home/<int:home_id>/delete', methods=['GET','POST'])
@login_required
@limiter.limit('5 per day', exempt_when= lambda : current_user.email == current_app.config['MAIL_USERNAME'])
def delete_home(home_id):
    home = Home.query.get_or_404(home_id)
    if current_user.email != current_app.config['MAIL_USERNAME']:
        abort(403)
    if request.method == 'GET':
        flash("Since I was on GET DELETE, home has not been deleted!", 'warning')
        return redirect(url_for('main.home'))
    db.session.delete(home)
    db.session.commit()   
    flash('Home has been deleted!', 'success')
    return redirect(url_for('main.home'))

@main.route('/project')
def project():
    home = Home.query.order_by(Home.id.desc()).first_or_404()
    admin_task = home.task
    admin_email = current_app.config['MAIL_USERNAME']
    ## page and sort_category query parmeters from url
    page = request.args.get('page', 1, type=int)
    sort_category = request.args.get('sort_category', 'All', type=str)
    if sort_category == 'All':
        projects = Project.query.order_by(Project.date.desc()).paginate(page=page, per_page=5) 
    elif sort_category == 'AI' or sort_category == 'Web' or sort_category == 'Electronic':
        projects = Project.query.filter_by(category=sort_category).order_by(Project.date.desc()).paginate(page=page, per_page=5) 
    else:
        abort(404)
    return render_template('project_overview.html', title='Project Page', admin_email=admin_email, admin_task=admin_task, uniform=True, projects=projects, sort_category=sort_category)

mywebsite/users/routes.py
from flask import render_template, flash, redirect, url_for, request, session, current_app, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from mywebsite import db, bcrypt, limiter
from mywebsite.users.forms import (RegistrationForm, LoginForm, AccountForm,
                                   RequestResetForm, ResetPasswordForm)
from mywebsite.models import Home, User, Comment
from mywebsite.users.utils import save_image, delete_image, send_thread_reset_email
from datetime import datetime
import timeago


users = Blueprint('users', __name__) #string users is the directory users, __name__ is where it located


@users.route('/register', methods=['GET', 'POST'])
def register():
    home = Home.query.order_by(Home.id.desc()).first_or_404()
    admin_task = home.task
    admin_email = current_app.config['MAIL_USERNAME']
    if current_user.is_authenticated:
        return redirect(url_for('main.project'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f"You've been successfully created account!", 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register Page', admin_email=admin_email, admin_task=admin_task, form=form, footer=True)

@users.route('/login',  methods=['GET', 'POST'])
# @limiter.limit('100 per day;50 per hour', exempt_when= lambda : current_user.is_authenticated) #also the limit of login GET depend on the limit of another routes
def login(): #Note about login: GET -> POST-> REDIRECT
    home = Home.query.order_by(Home.id.desc()).first_or_404()
    admin_task = home.task
    admin_email = current_app.config['MAIL_USERNAME']
    #save previous url after hit login with method=GET
    if request.method == 'GET':
        session['url'] = request.referrer
    #redirect to project route after authenticate user
    if current_user.is_authenticated:
        return redirect(url_for('main.project'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.attempt < 5 and bcrypt.check_password_hash(user.password, form.password.data):
            #Guess: login_user -> login_manager ->  UserMixin 
            # -> is_authenticated, is_active, is_anonymous and get_ID take 2 parameters (user, login_manager.user_loader)
            login_user(user, remember=form.remember.data)
            user.attempt = 0
            db.session.commit()
            flash(f"You've been successfully logged in!", 'success')
            next = request.args.get('next')
            if next: #redirect to the next page if next existed
                return redirect(next) #next page
            else: #redirect to the previous page(previous url) if next not existed
                previous = session.get('url') 
                if previous:
                    return redirect(previous)
                else: #come to this point because the user paste the login address to url bar in the browser
                    return redirect(url_for('main.project'))
        else:
            count = 0
            if user: # increase login attempt when login failed for the user in the database
                user.attempt += 1
                if user.attempt >= 5:
                    user.attempt = 5
                db.session.commit()
                count = user.attempt
            if count <= 4: #login FAIL
                flash('Login unsuccessful. Please check your email and password', 'danger')
            else: #login FAIL
                flash('This account has been blocked for security reasons', 'danger')
                flash('If you own this account, please click on Reset Password', 'warning')
    return render_template('login.html', title='Login Page', admin_email=admin_email, admin_task=admin_task, form=form)


@users.route('/logout')
def logout():
    logout_user()
    flash(f"You've been successfully logged out!", 'success')
    return redirect(url_for('users.login'))

@users.route('/account', methods=['GET', 'POST'])
@login_required
@limiter.limit('200 per day;120 per hour', exempt_when= lambda : current_user.email == current_app.config['MAIL_USERNAME'])
def account():
    # about admin
    home = Home.query.order_by(Home.id.desc()).first_or_404()
    admin_task = home.task
    admin_email = current_app.config['MAIL_USERNAME']
    #check validated on submit
    form = AccountForm()
    if form.validate_on_submit(): #post method
        current_user.username = form.username.data
        current_user.email = form.email.data
        is_saved = False
        if form.image.data:
            old_image_file = current_user.image
            image_file = save_image(form.image.data)
            current_user.image = image_file
            is_saved = True
        db.session.commit()
        if is_saved:#delete old image after it update new image
            delete_image(old_image_file)
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET': #get method
        form.username.data = current_user.username
        form.email.data = current_user.email
    image = url_for('static', filename='images/user/' + current_user.image)
    return render_template('account.html', title='Account Page ', admin_email=admin_email, admin_task=admin_task, image=image, form=form)

@users.route('/view_comments/<username>')
def view_user_comments(username):
    home = Home.query.order_by(Home.id.desc()).first_or_404()
    admin_task = home.task
    admin_email = current_app.config['MAIL_USERNAME']
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    pagination_comments = Comment.query.filter_by(author=user).order_by(Comment.date.desc()).paginate(page=page, per_page=10)
    now = datetime.utcnow() # current time 
    readable_dates = [timeago.format(comment.date, now) for comment in pagination_comments.items] # timeago for comments
    readable_comments = zip(pagination_comments.items, readable_dates) # timeago for comments
    return render_template('view_user_comments.html', title='User Comments Page', admin_email=admin_email, admin_task=admin_task, user=user, pagination_comments=pagination_comments, readable_comments=readable_comments, uniform=True)

# step1 of reset password: request 
# request take innput from form. it means take email
# by query that input email got the user in database
# since got a user in database call send_reset_email
@users.route('/reset_password', methods=['GET', 'POST'])
@limiter.limit('10 per day') #10 because try to avoid spam email
def reset_request():
    home = Home.query.order_by(Home.id.desc()).first_or_404()
    admin_task = home.task
    admin_email = current_app.config['MAIL_USERNAME']
    if current_user.is_authenticated:
        return redirect(url_for('main.project'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first_or_404()
        try:
            send_thread_reset_email(user)
        except:
            abort(500)
        flash('An email has been sent with a link to reset your password', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Request Password Page', admin_email=admin_email, admin_task=admin_task, form=form)


# step 3 of reset password: verify token and enter new password
#input step 3 form the link in send email from step 2
#when click on valid link it, this route will verify the token 
# if it is an invalid token, then it redirect to reset_request route
# if it is a valid token, then it render templater for enter new password
@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.project'))
    user = User.verify_reset_token(token) #it's defined in models.py
    if user is None:
        flash('That token is invalid or expired', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        user.attempt = 0
        db.session.commit()
        flash(f"You've been successfully updated password!", 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password Page', form=form)

mywebsite/templates/before_delete_home.html
{% macro delete_home_popup(home) %}
<div class="modal fade p-5" id="delete_home_{{home.id}}" tabindex="-1" role="dialog" aria-labelledby="delete_home_{{home.id}}Label" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header p-0">
                <h5 class="modal-title p-2" id="delete_home_{{home.id}}Label">Are you sure want to delete this home ?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true" class="p-1">&times;</span>
                </button>
            </div>
            <div class="modal-footer p-0">
                <button type="button" class="btn btn-secondary m-3" data-dismiss="modal">Cancel</button>
                <form action="{{ url_for('main.delete_home', home_id=home.id) }}" method="post">
                    <input class="btn btn-danger nn-one-click" type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>
{% endmacro %}

{% extends 'layout.html' %}
{% block content %}   
    <div class='nn-project'>
        <article class="mb-0 pb-0">
            {% for home in homes %}
                <div class='mb-5 p-3'style="border: 2px solid  ; border-radius: 5px;">
                    {% if current_user.is_authenticated  and current_user.email == admin_email %}
                        <button  type='button' class="btn btn-danger mr-3" data-toggle="modal" data-target="#delete_home_{{home.id}}">Delete This Home</button>
                        <p class="text-muted text-center m-auto">{{ home.date.strftime('%c') }} </p>
                        {{ delete_home_popup(home) }} 
                    {% endif %}
                    {{ home.about_me | safe }}
                </div>
            {% endfor %}
        </article>
    </div>
{% endblock content %}

mywebsite/templates/project_detail.html
{% macro delete_project_popup(project) %}
<div class="modal fade p-5" id="delete_project_{{project.id}}" tabindex="-1" role="dialog" aria-labelledby="delete_project_{{project.id}}Label" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header p-0">
                <h5 class="modal-title p-2" id="delete_project_{{project.id}}Label">Are you sure want to delete this project ?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true" class="p-1">&times;</span>
                </button>
            </div>
            <div class="modal-footer p-0">
                <button type="button" class="btn btn-secondary m-3" data-dismiss="modal">Cancel</button>
                <form action="{{ url_for('projects.delete_project', project_id=project.id) }}" method="post">
                    <input class="btn btn-danger nn-one-click" type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>
{% endmacro %}
{% macro comment_popup(comment,  do) %}
    <div class="modal fade p-5" id="{{do}}_comment_{{comment.id}}" tabindex="-1" role="dialog" aria-labelledby="{{do}}_comment_{{comment.id}}Label" aria-hidden="true">
        <div class="modal-dialog" role="document" style="width: 70vw;">
            <div class="modal-content">
                <div class="modal-header p-2">
                    <h5 class="modal-title" id="{{do}}_comment_{{comment.id}}Label">Are you sure want to {{ do }} this comment?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer p-0">
                    {% if do == 'update' %}
                        <form action="{{ url_for('comments.update_comment', comment_id=comment.id) }}" method="post">
                            <textarea class='form-control m-auto' name="forming" cols="50" rows="10">{{ comment.content }}</textarea>
                            <input class="btn btn-primary d-inline float-right mr-2 nn-one-click" type="submit" value="Update">
                            <button type="button" class="btn btn-secondary d-inline float-right mr-2" data-dismiss="modal">Cancel</button>
                            
                    {% elif do == 'delete' %}
                        <button type="button" class="btn btn-secondary m-3" data-dismiss="modal">Cancel</button>
                        <form action="{{ url_for('comments.delete_comment', comment_id=comment.id) }}" method="post">
                            <input class="btn btn-danger nn-one-click" type="submit" value="Delete">
                    {% endif %}
                        </form>
                </div>
            </div>
        </div>
    </div>
{% endmacro %}


{% extends 'layout.html' %}
{% block content %}   
    <div class='nn-project'>
        <article class="mb-0 pb-0">
            {% if current_user.is_authenticated  and current_user.email == admin_email %}
                <div>
                    {% if is_aidotpy_failed %}
                        <div class=" mb-2 pt-1 pb-1 pl-2 pr-2 rounded bg-danger" style="width: max-content;">Failure in ai.py file</div>
                    {% else %}
                        <div class=" mb-2 pt-1 pb-1 pl-2 pr-2 rounded" style="width: max-content; background-color: #17a2b8;">ai.py file can work</div>
                    {% endif %}
                    <a class="btn btn-primary d-inline btn-lg mr-2 nn-one-click p-1" href="{{ url_for('projects.update_project', project_id=project.id) }}">Update Project</a>
                    <button  type='button' class="btn btn-danger d-inline m-1 p-1" data-toggle="modal" data-target="#delete_project_{{project.id}}">Delete Project</button>
                    {{ delete_project_popup(project) }} 
                    <br> <br>
                </div>
            {% endif %}
            <h2> {{ project.title }}</h2>
            <p><a class='nn-category' href="{{ url_for('main.project', sort_category=project.category, page=1) }}">{{ project.category }}</a> - <span class="text-muted">{{ project.date.strftime('%b %e, %Y') }}</span></p>
            <div>
                {{ project.content | safe }}
                {% if current_user.is_authenticated %}
                    {% if not is_aidotpy_failed %}
                        {% if project.model_name %} {# if project.model_name != '' it means AI category then show run button #}
                            <div style="background-color: white">
                                <form  action="" method="POST" enctype="multipart/form-data">
                                    {{ ai_form.hidden_tag() }}
                                    <div class='form-group'>
                                        {% if project.need_input == 'No' %} 
                                            {{ ai_form.input(class='form-control-file p-0 nn-file-select nn-no-input') }}
                                        {% else %}
                                            {{ ai_form.input(class='form-control-file p-0 nn-file-select', required=True) }}
                                            {% if ai_form.input.errors %}
                                                {% for error in ai_form.input.errors %}
                                                    <span class='text-danger'>{{ error }} </span>
                                                {% endfor %}
                                            {% endif %}
                                        {% endif %}
                                    </div>
                                    <div class='form-group'>
                                        {{ ai_form.submit(class='btn btn-sm btn-primary float-left mt-0 p-1 mb-5 nn-one-click') }}
                                    </div>
                                </form>
                            </div>
                        {% endif %}
                    {% else %}
                        {% if project.category == 'AI' %}
                            {% if current_user.email == admin_email%}
                                <div class="p-1 rounded bg-danger" style="width: max-content;">Since current ai.py is failure, there is no run button right here. I must to update ai.py file by click on Update Project button</div>
                            {% else %}
                                <div>The run model will be coming later \(^_^)/</div>
                            {% endif %}
                        {% endif %}
                    {% endif %}
                {% else %}
                    {% if project.category == 'AI'%}
                        <p class='text-muted'>
                            Please  
                            <a class='font-weight-bold nn-link-color' href="{{ url_for('users.login') }}">login</a>
                            to run model
                        </p> 
                    {% endif %}
                {% endif %}
            </div>
            <br> <br>
        </article>
        {% if output %}
            {{ output | safe }}
        {% endif %}
        
        {% if current_user.is_authenticated %}
            <form action="" method="POST">
                {{ comment_form.hidden_tag() }}
                <div class='form-group'>
                    {{ comment_form.content.label(class='font-weight-bold d-flex') }}
                    {% if comment_form.content.errors %}
                        {{ comment_form.content(class='form-control form-control-lg is-invalid') }}
                        <div class='invalid-feedback'>
                            {% for error in comment_form.content.errors %}
                                <span>{{ error }} </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        <div>
                            {{ comment_form.content(class='form-control form-control-lg mt-0') }}
                        </div>
                    {% endif %}
                </div>
                <div class='form-group'>
                    {{ comment_form.submit(class='btn btn-primary btn-sm nn-one-click') }}
                </div>
            </form>
        {% else %}
            <h5 class="font-weight-bold m-0">Leave a Reply</h5>
            <p class='text-muted mb-0'>
                You must be 
                <a class='font-weight-bold nn-link-color' href="{{ url_for('users.login') }}">login</a>
                to post comment
            </p> 
        {% endif %}
        
        <div class="font-weight-bold mb-1 mt-0">Comments ({{ pagination_comments.total }})</div> 
        {% for comment, readable_date in readable_comments %}
            <div class='d-flex bg-info rounded mb-3' >
                <div class='d-flex mt-2 mb-2 ml-1'>
                    <div class=' ml-2 mr-3'>
                        <a href="{{ url_for('users.view_user_comments', username=comment.author.username) }}">
                            <img class=' rounded-circle m-auto mt-2' style="width: 3rem; height: 3rem;" src="{{ url_for('static', filename='images/user/' + comment.author.image)}}">
                        </a>
                    </div>
                    <div> 
                        <div>
                            <a href="{{ url_for('users.view_user_comments', username=comment.author.username) }}"><h6 class='mt-2 font-weight-bold d-inline nn-color'>{{ comment.author.username}}  </h6></a>
                            <h6 class='text-muted d-inline'> said {{ readable_date }}</h6>
                            <p>{{ comment.content }}</p>
                        </div>
                        {% if current_user.is_authenticated %}
                            <div class='mt-2 mb-0 pb-0'>
                                {% if comment.author == current_user %}
                                    <button type='button' class="btn btn-outline-primary btn-sm d-inline pl-1 pl-1 pt-0 pb-0 m-1" data-toggle="modal" data-target="#update_comment_{{comment.id}}"> <i class="fas fa-edit"></i><small>Edit </small></button>
                                     {{ comment_popup(comment, 'update') }} 
                                {% endif %}
                                {% if current_user.email == admin_email or comment.author == current_user %}
                                    <button type='button' class="btn btn-outline-danger btn-sm d-inline pl-1 pl-1 pt-0 pb-0 m-1" data-toggle="modal" data-target="#delete_comment_{{comment.id}}"> <i class="fas fa-trash-alt"></i><small>Delete </small></button>
                                    {{ comment_popup(comment, 'delete') }}
                                {% endif %}
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
        {% if pagination_comments.pages > 1 %}
            <div class='text-center'>
                {% for page_number in pagination_comments.iter_pages(left_current=1, right_current=2, left_edge=1, right_edge=1) %}
                    {% if page_number %}
                        {% if page_number == pagination_comments.page %}
                            <a class='btn btn-info mb-5 d-inline' href="{{ url_for('projects.project', project_id=project.id, page=page_number) }}">{{ page_number}}</a>
                        {% else %}
                            <a class='btn btn-outline-info mb-5 d-inline' href="{{ url_for('projects.project', project_id=project.id, page=page_number) }}">{{ page_number}}</a>
                        {% endif %}
                    {% else %}
                        ...
                    {% endif %}
                {% endfor %}
                <br><br>
            </div>
        {% endif %}
        
    </div>
{% endblock content %}

mywebsite/templates/reset_request.html
{% extends 'layout.html' %}

{% block top %}
        <div class="nn-text">
            <h2>Reset Password</h2>
        </div>
        <div class="nn-light-text">
            <h2>Email in, password out</h2>
        </div>
        <div class="nn-form container">
            <form action="" method="POST">
                {{ form.hidden_tag() }}
                <div class='form-group'>
                    {{ form.email.label(class='form-control-label mt-5') }}
                    {% if form.email.errors %}
                        {{ form.email(class='form-control form-control-lg is-invalid') }}
                        <div class='invalid-feedback'>
                            {% for error in form.email.errors %}
                                <span>{{ error }} </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
                <div class='form-group'>
                    {{ form.submit(class='btn btn-primary') }}
                </div>
                <br>
            </form>
        </div>
{% endblock top%}